### ISSUE TITLE
Will it work on Redmi 4 Prime?  

### ISSUE THREAD

**Issue by nurmohammed840** [Giovix92/EDLUnlock#2]
My [redmi 4 prime](https://www.gsmarena.com/xiaomi_redmi_4_prime-8263.php) has same processor (MSM8953),

You said that,
> Plus, the bin folder only contains MSM8953 patched mbn file. You'll need a working .mbn/.elf file (patched, hehe) in order to use the tool correctly, at least on other platforms

You also mention that,
>Inside the repo there already is a `.mbn` file + the partition (with its specific rawprogram0.xml file) for unlocking a Mi A1 (tissot) thru EDL mode.

So will it work on my device ?

**Comment by Giovix92** [comment]
Yeah it should work fine.

**Comment by nurmohammed840** [comment]
It did not work...

```
Version 2.15
Downloading flash programmer: E:\hack_with_edl\EDLUnlock\\bin\prog_emmc_firehose_8953_ddr.mbn
Successfully open flash programmer to write: E:\hack_with_edl\EDLUnlock\\bin\prog_emmc_firehose_8953_ddr.mbn
Waiting for flash programmer to boot

Programming device using SECTOR_SIZE=512

<?xml version = "1.0" ?><data><configure MemoryName="emmc" ZLPAwareHost="1" SkipStorageInit="0" SkipWrite="0" MaxPayloadSizeToTargetInBytes="16384"/></data>
<?xml version="1.0" encoding="UTF-8" ?><data><log value="logbuf@0x0806CEC0 fh@0x08069D28" /></data>
<?xml version="1.0" encoding="UTF-8" ?><data><response value="ACK" MinVersionSupported="1" MemoryName="eMMC" MaxPayloadSizeFromTargetInBytes="4096" MaxPayloadSizeToTargetInBytes="16384" MaxPayloadSizeToTargetInBytesSupported="1048576" MaxXMLSizeInBytes="4096" Version="1" TargetName="8953" /></data>

<?xml version="1.0" encoding="UTF-8" ?><data><log value="logbuf@0x0806CEC0 fh@0x08069D28" /></data>me="eMMC" MaxPayloadSizeFromTargetInBytes="4096" MaxPayloadSizeToTargetInBytes="16384" MaxPayloadSizeToTargetInBytesSupported="1048576" MaxXMLSizeInBytes="4096" Version="1" TargetName="8953" /></data>

Connected to flash programmer, starting download
start_sector: 1052672 physical_partition_number: 0 num_partition_sectors: 2048 filename: devinfo.img file_sector_offset: 0
Sparse image not detected -- loading binary
In offset: 0 out offset: 1052672 sectors: 2048
<?xml version="1.0" ?><data>
<program SECTOR_SIZE_IN_BYTES="512" num_partition_sectors="2048" physical_partition_number="0" start_sector="1052672"/>
</data>
<?xml version="1.0" encoding="UTF-8" ?><data><log value="start 1052672, num 2048" /></data>
<?xml version="1.0" encoding="UTF-8" ?><data><response value="ACK" rawmode="true" /></data>
<?xml version="1.0" encoding="UTF-8" ?><data><log value="Finished sector address 1054720" /></data>
<?xml version="1.0" encoding="UTF-8" ?><data><response value="ACK" rawmode="false" /></data>
Status: 0 The operation completed successfully.


[i] All done!
```
But I checked via:

```
❯ fastboot oem device-info
(bootloader)    Device tampered: false
(bootloader)    Device unlocked: false
(bootloader)    Device critical unlocked: false
(bootloader)    Charger screen enabled: true
(bootloader)    Display panel: 
OKAY [  0.053s]
Finished. Total time: 0.055s
```
What did I wrong ?

**Comment by Giovix92** [comment]
Looks ok from the log. Could you dump the devinfo.img? I'll take a look at it.

**Comment by nurmohammed840** [comment]
> Looks ok from the log. Could you dump the devinfo.img? I'll take a look at it.

Of course,  How do I capture my `devinfo.img` ?

I tried: `c:\Python27\python.exe .\firehorse.py -c COM8 -t mido target read_partition devinfo` in EDL mode, My device codename is not `mido`, But `markw`, which [firehorse](https://github.com/alephsecurity/firehorse) does not support it, But I run it anyway... 

I got this: 

```
INFO: Downloading partition devinfo to mido-devinfo-read.bin...
Traceback (most recent call last):
  File ".\firehorse.py", line 119, in <module>
    main()
  File ".\firehorse.py", line 113, in main
    cmds[name](args)
  File "E:\hack_with_edl\firehorse\host\target.py", line 102, in do_cmd
    fw.Framework.read_partition(args[1])
  File "E:\hack_with_edl\firehorse\host\fw.py", line 141, in read_partition
    Framework.firehose(xml)
  File "E:\hack_with_edl\firehorse\host\fw.py", line 290, in firehose
    return Framework.firehosep("../tmp/temp.xml")
  File "E:\hack_with_edl\firehorse\host\fw.py", line 338, in firehosep
    stdout=subprocess.PIPE, stdin=subprocess.PIPE)
  File "c:\Python27\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "c:\Python27\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

It just create `temp.xml`,

```xml
<?xml version="1.0" ?>
<data>
<read SECTOR_SIZE_IN_BYTES="512" file_sector_offset="0" filename="mido-devinfo-read.bin" label="devinfo" num_partition_sectors="2048" physical_partition_number="0" size_in_KB="1024.0" sparse="true" start_byte_hex="0x20200000" start_sector="1052672"/>
</data>
```

Note: I changed `rawprogram0.xml` where `start_byte_hex="0x20200000" start_sector="1052672"`, I confirm this value from two official fastboot rom also, 
1. MIUI v10.2.2
2. MIUI v8.1.0

Both rom has this same line:

```xml
<program SECTOR_SIZE_IN_BYTES="512" file_sector_offset="0" filename="" label="devinfo" num_partition_sectors="2048" physical_partition_number="0" size_in_KB="1024.0" sparse="true" start_byte_hex="0x20200000" start_sector="1052672"/> 
```

I flash with this value:

```xml
<program SECTOR_SIZE_IN_BYTES="512" file_sector_offset="0" filename="devinfo.img" label="devinfo" num_partition_sectors="2048" physical_partition_number="0" size_in_KB="1024.0" sparse="false" start_byte_hex="0x20200000" start_sector="1052672"/>
```

**Comment by nurmohammed840** [comment]
I also tried: 
```
> .\emmcdl.exe -p com8 -disk_sector_size 512 -d devinfo -o ./devinfo.bin
```

Got:

```
Dumping data to file ./devinfo.bin
Dumping at start sector: 0 for sectors: 0 to file: ./devinfo.bin
Finding all devices in emergency download mode...
Qualcomm HS-USB QDLoader 9008 (COM8)

Finding all disks on computer ...
\\.\PhysicalDrive8Successfully opened volume
Status: 2 The system cannot find the file specified.
```

Surly I enter some wrong input, So what is value of `<PartName>` ?
```
.\emmcdl.exe -p com8 -disk_sector_size 512 -d <PartName> -o ./devinfo.bin
```

**Comment by Giovix92** [comment]
> I also tried:
> 
> ```
> > .\emmcdl.exe -p com8 -disk_sector_size 512 -d devinfo -o ./devinfo.bin
> ```
> 
> Got:
> 
> ```
> Dumping data to file ./devinfo.bin
> Dumping at start sector: 0 for sectors: 0 to file: ./devinfo.bin
> Finding all devices in emergency download mode...
> Qualcomm HS-USB QDLoader 9008 (COM8)
> 
> Finding all disks on computer ...
> \\.\PhysicalDrive8Successfully opened volume
> Status: 2 The system cannot find the file specified.
> ```
> 
> Surly I enter some wrong input, So what is value of `<PartName>` ?
> 
> ```
> .\emmcdl.exe -p com8 -disk_sector_size 512 -d <PartName> -o ./devinfo.bin
> ```

The partname should be devinfo, as the image name states.  
If you found that image on the fastboot package, then it should match the partition name.  
Check if the COM port is correct (check in device manager, I'm assuming you're using Windows). Also, try this to dump your image:
`emmcdl.exe -p <COMPORT> -f <FIREHOSEPATH> -d devinfo -o devinfo.img`

NOTE: If you want to give a shot at flashing it, firstly TAKE A BACKUP OF YOUR GPT, then you could use:
`emmcdl.exe -p <COMPORT> -f <FIREHOSEPATH> -b devinfo devinfo.img`

Probably your try didn't work due to the missing firehose path, and because windows uses `\` instead of `/`.

**Comment by nurmohammed840** [comment]
What is the different between: `emmcdl.exe ... -b devinfo devinfo.img`  and  `emmcdl.exe ... -x <Program XML file>` ?

Also note that, this command does not work, `emmcdl.exe -p <COMPORT> -r`  It give me this error:

```
Version 2.15
Status: 6 The handle is invalid.
```

**Comment by nurmohammed840** [comment]
I found out that, though flashed complete successfully, But It didn't write at `devinfo` partition,

I did:

```
> .\emmcdl.exe -p com8 -f prog_emmc_firehose_8953_ddr.mbn -d devinfo -o devinfo.img
``` 

Then set `x10` and `x18`  to `01` (Little Endian) in hex editor. And flashed it with,

```
> .\emmcdl.exe -p com8 -f prog_emmc_firehose_8953_ddr.mbn -b devinfo devinfo.img
``` 

Then delete `devinfo.img` and read it again:

```
> .\emmcdl.exe -p com8 -f prog_emmc_firehose_8953_ddr.mbn -d devinfo -o devinfo.img
```

But `devinfo.img` did not changed! 😨 Why ?  

My device got lock via MI account (which is not mine), Now Its completely useless, I tried to contact with xiomi global, they said that couldn't unlock it, due to security policy! Well don't need this account and I don't care, I just want to remove it, so that I can use my hardware...

So I thought, If I able to unlock bootloader, I could flash TWRP, and install Custom OS... 
Is there any other tool for  flashing ?

**Comment by Giovix92** [comment]
> What is the different between: `emmcdl.exe ... -b devinfo devinfo.img` and `emmcdl.exe ... -x <Program XML file>` ?  

`-x` uses an xml file for parsing options, such as flashing partitions.

> 
> Also note that, this command does not work, `emmcdl.exe -p <COMPORT> -r` It give me this error:
> 
> ```
> Version 2.15
> Status: 6 The handle is invalid.
> ```
`-r` stands for `reset`. You're still missing the mbn file inside the command.




> ...
> But `devinfo.img` did not changed! fearful Why ?

You need to pick an unlocked devinfo.img for your device then, can't think of anything else.

> My device got lock via MI account (which is not mine), Now Its completely useless, I tried to contact with xiomi global, they said that couldn't unlock it, due to security policy! Well don't need this account and I don't care, I just want to remove it, so that I can use my hardware...

Well it's pretty normal and I'm with their position too. Can't really attest if this is your device or not.
 
> So I thought, If I able to unlock bootloader, I could flash TWRP, and install Custom OS... Is there any other tool for flashing ?

Nope, there isn't any other tool to do that. You could try with other all-in-one edl software (won't mention any name), or ask someone to miflash it through edl (with an authorized account, you'll find plenty inside telegram).

**Comment by Giovix92** [comment]
Closing, no more updates on this.

**Comment by Giovix92** [comment]
Closing, no more updates on this.
