### ISSUE TITLE
Problem on Note 4x (mido)

### ISSUE THREAD

**Issue by ludaka** [Giovix92/EDLUnlock#3]
hey i tried your tool on my redmi note 4x (mido) i correct rawprogram0.xml to my device also tried your devinfo.img and my own .img / bin files
After i edit it and re-dump em its  modified .. but after i start phone bootloader is not unlocked :
(bootloader)    Device tampered: false
(bootloader)    Device unlocked: false
(bootloader)    Device critical unlocked: false
(bootloader)    Charger screen enabled: false
(bootloader)    Display panel:
Then i redump it.. and its like i never edited it all changes that i (they are reverted to stock) ? Is it some write protection on Mido? 

I find one guy in xda forum that already dump bootloaders on 2-3 device one of them is mido and here is how unlocked boot loader need to look 

tijoro@local:~/tmp devinfo$ hexdump -C devinfo-mido.img
00000000 41 4e 44 52 4f 49 44 2d 42 4f 4f 54 21 00 00 00 |ANDROID-BOOT!...|
00000010 01 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00 |................|
00000020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |................|
*
000000e0 01 00 00 00 15 53 8a 17 83 99 ce 55 db a2 19 e5 |.....S.....U....|

After i flash with same edit like his dump still phone revert changes after boot up

**Comment by Giovix92** [comment]
The devinfo file looks fine to me. Did you flash it correctly? Because it may need a different hex start position.

You could pick it from any fastboot rom if I'm not mistaken, there should be a rawprogram0.xml file somewhere in it.

**Comment by ludaka** [comment]
We can closed it.. I think this method is patched on my phone bcs it revert all changes that I make
